# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/microblaze_v_preset/microblaze_v_preset.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_v_preset || ORIG_REF_NAME==microblaze_v_preset} -quiet] -quiet

# IP: bd/microblaze_v_preset/ip/microblaze_v_preset_axi_timer_0_0/microblaze_v_preset_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_v_preset_axi_timer_0_0 || ORIG_REF_NAME==microblaze_v_preset_axi_timer_0_0} -quiet] -quiet

# IP: bd/microblaze_v_preset/ip/microblaze_v_preset_axi_uartlite_0_0/microblaze_v_preset_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_v_preset_axi_uartlite_0_0 || ORIG_REF_NAME==microblaze_v_preset_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/microblaze_v_preset/ip/microblaze_v_preset_microblaze_riscv_0_xlconcat_0/microblaze_v_preset_microblaze_riscv_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_v_preset_microblaze_riscv_0_xlconcat_0 || ORIG_REF_NAME==microblaze_v_preset_microblaze_riscv_0_xlconcat_0} -quiet] -quiet

# IP: bd/microblaze_v_preset/ip/microblaze_v_preset_clk_wiz_1_0/microblaze_v_preset_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_v_preset_clk_wiz_1_0 || ORIG_REF_NAME==microblaze_v_preset_clk_wiz_1_0} -quiet] -quiet

# IP: bd/microblaze_v_preset/ip/microblaze_v_preset_rst_clk_wiz_1_100M_0/microblaze_v_preset_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_v_preset_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==microblaze_v_preset_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/microblaze_v_preset_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_v_preset_smartconnect_0_0 || ORIG_REF_NAME==microblaze_v_preset_smartconnect_0_0} -quiet] -quiet

# IP: bd/microblaze_v_preset/ip/microblaze_v_preset_microblaze_riscv_0_axi_intc_1/microblaze_v_preset_microblaze_riscv_0_axi_intc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_v_preset_microblaze_riscv_0_axi_intc_1 || ORIG_REF_NAME==microblaze_v_preset_microblaze_riscv_0_axi_intc_1} -quiet] -quiet

# IP: bd/microblaze_v_preset/ip/microblaze_v_preset_mdm_riscv_0_0/microblaze_v_preset_mdm_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_v_preset_mdm_riscv_0_0 || ORIG_REF_NAME==microblaze_v_preset_mdm_riscv_0_0} -quiet] -quiet

# IP: bd/microblaze_v_preset/ip/microblaze_v_preset_microblaze_riscv_0_2/microblaze_v_preset_microblaze_riscv_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_v_preset_microblaze_riscv_0_2 || ORIG_REF_NAME==microblaze_v_preset_microblaze_riscv_0_2} -quiet] -quiet

# IP: bd/microblaze_v_preset/ip/microblaze_v_preset_dlmb_v10_2/microblaze_v_preset_dlmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_v_preset_dlmb_v10_2 || ORIG_REF_NAME==microblaze_v_preset_dlmb_v10_2} -quiet] -quiet

# IP: bd/microblaze_v_preset/ip/microblaze_v_preset_ilmb_v10_2/microblaze_v_preset_ilmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_v_preset_ilmb_v10_2 || ORIG_REF_NAME==microblaze_v_preset_ilmb_v10_2} -quiet] -quiet

# IP: bd/microblaze_v_preset/ip/microblaze_v_preset_dlmb_bram_if_cntlr_2/microblaze_v_preset_dlmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_v_preset_dlmb_bram_if_cntlr_2 || ORIG_REF_NAME==microblaze_v_preset_dlmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/microblaze_v_preset/ip/microblaze_v_preset_ilmb_bram_if_cntlr_2/microblaze_v_preset_ilmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_v_preset_ilmb_bram_if_cntlr_2 || ORIG_REF_NAME==microblaze_v_preset_ilmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/microblaze_v_preset/ip/microblaze_v_preset_lmb_bram_2/microblaze_v_preset_lmb_bram_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_v_preset_lmb_bram_2 || ORIG_REF_NAME==microblaze_v_preset_lmb_bram_2} -quiet] -quiet

# XDC: /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/microblaze_v_preset_ooc.xdc
