# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.runs/synth_1/microblaze_v_preset_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
set_param bd.open.in_stealth_mode 1
set_msg_config  -id {Synth 8-256}  -suppress 
set_msg_config  -id {Synth 8-5545}  -suppress 
set_msg_config  -id {Synth 8-5546}  -suppress 
set_msg_config  -id {Opt   31-422}  -suppress 
set_msg_config  -id {HDL 9-2216}  -suppress 
set_msg_config  -id {HDL 9-1061}  -suppress 
set_msg_config  -id {Runs 36-5}  -suppress 
set_msg_config  -id {VRFC 10-163}  -suppress 
set_msg_config  -id {VRFC 10-165}  -suppress 
set_msg_config  -id {Simtcl 6-16}  -suppress 
set_msg_config  -id {Simtcl 6-17}  -suppress 
set_msg_config  -id {Synth 8-113}  -suppress 
set_msg_config  -id {Constraints 18-4434}  -suppress 
set_msg_config  -id {Drc 23-20}  -suppress 
set_msg_config  -id {DRC CHECK-3}  -suppress 
set_msg_config  -id {DRC DPIP-1}  -suppress 
set_msg_config  -id {DRC DPOP-1}  -suppress 
set_msg_config  -id {DRC DPOP-2}  -suppress 
set_msg_config  -id {DRC LOCE-1}  -suppress 
set_msg_config  -id {DRC RTSTAT-10}  -suppress 
set_msg_config  -id {DRC REQP-1839}  -suppress 
set_msg_config  -id {DRC REQP-1840}  -suppress 
set_msg_config  -id {Synth 8-226}  -suppress 
set_msg_config  -id {Drc REQP-1857]}  -suppress 
set_msg_config  -id {Drc REQP-1858]}  -suppress 
set_msg_config  -id {DRC REQP-181}  -suppress 
set_msg_config  -id {DRC REQP-52}  -suppress 
set_msg_config  -id {BD 41-434}  -suppress 
set_msg_config  -id {Designutils 20-1318}  -suppress 
set_msg_config  -id {Common 17-301}  -suppress 
set_msg_config  -id {Pwropt 34-142}  -suppress 
set_msg_config  -id {Common 17-1361}  -suppress 
set_msg_config  -id {Vivado 12-4430}  -suppress 
set_msg_config  -id {Synth 8-312}  -suppress 
set_msg_config  -id {Vivado 12-1790}  -suppress 
set_msg_config  -id {Vivado 12-3645}  -suppress 
set_msg_config  -id {Project 1-486}  -suppress 
set_msg_config  -id {Project 1-560}  -suppress 
set_msg_config  -id {Designutils 20-1307}  -suppress 
set_msg_config  -id {filemgmt 56-12}  -suppress 
set_msg_config  -id {Vivado 12-5470}  -suppress 
set_msg_config  -id {Project 1-841}  -suppress 
set_msg_config  -id {Project 1-863}  -suppress 
set_msg_config  -id {Project 1-840}  -suppress 
set_msg_config  -id {Synth 8-4472}  -suppress 
set_msg_config  -id {Timing 38-3}  -new_severity {INFO} 
set_msg_config  -id {Synth 8-3848}  -new_severity {INFO} 
set_msg_config  -id {Synth 8-3936}  -new_severity {INFO} 
set_msg_config  -id {Synth 8-5733}  -new_severity {INFO} 
set_msg_config  -id {Synth 8-5858}  -new_severity {INFO} 
set_msg_config  -id {Constraints 18-550}  -new_severity {INFO} 
set_msg_config  -id {Vivado 12-1008}  -new_severity {INFO} 
set_msg_config  -id {Power 33-332}  -new_severity {INFO} 
set_msg_config  -id {Synth 8-3512}  -new_severity {ERROR} 
set_msg_config  -id {VRFC 10-664}  -new_severity {ERROR} 
set_msg_config  -id {Synth 8-4480}  -suppress 
set_msg_config  -id {filemgmt 20-1318}  -new_severity {ERROR} 
set_msg_config  -id {IP_Flow 19-1663}  -new_severity {ERROR} 
set_msg_config  -id {IP_Flow 19-11772}  -new_severity {ERROR} 
set_msg_config  -id {Vivado 12-508}  -new_severity {CRITICAL WARNING} 
set_msg_config  -id {Vivado 12-507}  -new_severity {CRITICAL WARNING} 
set_msg_config  -id {Vivado 12-627}  -new_severity {CRITICAL WARNING} 
set_msg_config  -id {Project 1-498}  -new_severity {CRITICAL WARNING} 
set_msg_config  -id {Synth 8-3330}  -new_severity {CRITICAL WARNING} 
set_msg_config  -id {Synth 8-3919}  -new_severity {CRITICAL WARNING} 
set_msg_config  -id {Synth 8-153}  -new_severity {CRITICAL WARNING} 
set_msg_config  -id {Synth 8-3331}  -suppress 
set_msg_config  -id {Synth 8-3295}  -new_severity {CRITICAL WARNING} 
set_msg_config  -id {Synth 8-5835}  -new_severity {CRITICAL WARNING} 
set_msg_config  -id {Route 35-328}  -new_severity {CRITICAL WARNING} 
set_msg_config  -id {Vivado 12-4430}  -new_severity {WARNING} 
set_msg_config  -id {Vivado 12-1387}  -new_severity {WARNING} 
set_msg_config  -id {BD 41-968}  -new_severity {WARNING} 
set_msg_config  -id {Vivado 12-1411}  -new_severity {ERROR} 
set_msg_config  -id {HDL 9-806}  -new_severity {ERROR} 
set_msg_config  -id {Opt 31-80}  -new_severity {ERROR} 
set_msg_config  -id {Route 35-14}  -new_severity {ERROR} 
set_msg_config  -id {Synth 8-3332}  -suppress 
set_msg_config  -id {AVAL-46}  -new_severity {ERROR} 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.cache/wt [current_project]
set_property parent.project_path /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths {/home/vid/.Xilinx/Vivado/2024.2/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part digilentinc.com:arty-a7-100:part0:1.1 [current_project]
set_property ip_output_repo /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files /home/vid/Desktop/VitisWorkspace/MicroBlaze_real_time/Debug/MicroBlaze_real_time.elf
set_property SCOPED_TO_REF microblaze_v_preset [get_files -all /home/vid/Desktop/VitisWorkspace/MicroBlaze_real_time/Debug/MicroBlaze_real_time.elf]
set_property SCOPED_TO_CELLS microblaze_riscv_0 [get_files -all /home/vid/Desktop/VitisWorkspace/MicroBlaze_real_time/Debug/MicroBlaze_real_time.elf]
read_vhdl -library xil_defaultlib /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/hdl/microblaze_v_preset_wrapper.vhd
add_files /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.srcs/sources_1/bd/microblaze_v_preset/microblaze_v_preset.bd
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_axi_timer_0_0/microblaze_v_preset_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_axi_timer_0_0/microblaze_v_preset_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_axi_uartlite_0_0/microblaze_v_preset_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_axi_uartlite_0_0/microblaze_v_preset_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_axi_uartlite_0_0/microblaze_v_preset_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_clk_wiz_1_0/microblaze_v_preset_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_clk_wiz_1_0/microblaze_v_preset_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_clk_wiz_1_0/microblaze_v_preset_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_rst_clk_wiz_1_100M_0/microblaze_v_preset_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_rst_clk_wiz_1_100M_0/microblaze_v_preset_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_rst_clk_wiz_1_100M_0/microblaze_v_preset_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_1/bd_15b6_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_1/bd_15b6_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_2/bd_15b6_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_3/bd_15b6_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_4/bd_15b6_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_5/bd_15b6_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_6/bd_15b6_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_7/bd_15b6_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_8/bd_15b6_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_9/bd_15b6_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_10/bd_15b6_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_11/bd_15b6_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_12/bd_15b6_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_13/bd_15b6_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_14/bd_15b6_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_15/bd_15b6_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_16/bd_15b6_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_20/bd_15b6_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_21/bd_15b6_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_22/bd_15b6_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_23/bd_15b6_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_24/bd_15b6_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_25/bd_15b6_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_29/bd_15b6_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_30/bd_15b6_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_31/bd_15b6_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_32/bd_15b6_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_33/bd_15b6_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_34/bd_15b6_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_35/bd_15b6_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_36/bd_15b6_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_37/bd_15b6_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_39/bd_15b6_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_40/bd_15b6_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_41/bd_15b6_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_42/bd_15b6_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_43/bd_15b6_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_44/bd_15b6_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_46/bd_15b6_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_47/bd_15b6_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_48/bd_15b6_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_49/bd_15b6_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_50/bd_15b6_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/bd_0/ip/ip_51/bd_15b6_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_smartconnect_0_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_microblaze_riscv_0_axi_intc_1/microblaze_v_preset_microblaze_riscv_0_axi_intc_1.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_microblaze_riscv_0_axi_intc_1/microblaze_v_preset_microblaze_riscv_0_axi_intc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_microblaze_riscv_0_axi_intc_1/microblaze_v_preset_microblaze_riscv_0_axi_intc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_mdm_riscv_0_0/microblaze_v_preset_mdm_riscv_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_mdm_riscv_0_0/microblaze_v_preset_mdm_riscv_0_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_microblaze_riscv_0_2/microblaze_v_preset_microblaze_riscv_0_2.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_microblaze_riscv_0_2/microblaze_v_preset_microblaze_riscv_0_2_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_microblaze_riscv_0_2/microblaze_v_preset_microblaze_riscv_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_dlmb_v10_2/microblaze_v_preset_dlmb_v10_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_ilmb_v10_2/microblaze_v_preset_ilmb_v10_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_dlmb_bram_if_cntlr_2/microblaze_v_preset_dlmb_bram_if_cntlr_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_ilmb_bram_if_cntlr_2/microblaze_v_preset_ilmb_bram_if_cntlr_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_lmb_bram_2/microblaze_v_preset_lmb_bram_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/microblaze_v_preset_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_microblaze_riscv_0_2/data/riscv_bootloop.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.srcs/utils_1/imports/synth_1/microblaze_v_preset_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top microblaze_v_preset_wrapper -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef microblaze_v_preset_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file microblaze_v_preset_wrapper_utilization_synth.rpt -pb microblaze_v_preset_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
