# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.runs/synth_1/neorv32_test_setup_bootloader.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
set_msg_config  -id {Synth 8-256}  -suppress 
set_msg_config  -id {Synth 8-5545}  -suppress 
set_msg_config  -id {Synth 8-5546}  -suppress 
set_msg_config  -id {Opt   31-422}  -suppress 
set_msg_config  -id {HDL 9-2216}  -suppress 
set_msg_config  -id {HDL 9-1061}  -suppress 
set_msg_config  -id {Runs 36-5}  -suppress 
set_msg_config  -id {VRFC 10-163}  -suppress 
set_msg_config  -id {VRFC 10-165}  -suppress 
set_msg_config  -id {Simtcl 6-16}  -suppress 
set_msg_config  -id {Simtcl 6-17}  -suppress 
set_msg_config  -id {Synth 8-113}  -suppress 
set_msg_config  -id {Constraints 18-4434}  -suppress 
set_msg_config  -id {Drc 23-20}  -suppress 
set_msg_config  -id {DRC CHECK-3}  -suppress 
set_msg_config  -id {DRC DPIP-1}  -suppress 
set_msg_config  -id {DRC DPOP-1}  -suppress 
set_msg_config  -id {DRC DPOP-2}  -suppress 
set_msg_config  -id {DRC LOCE-1}  -suppress 
set_msg_config  -id {DRC RTSTAT-10}  -suppress 
set_msg_config  -id {DRC REQP-1839}  -suppress 
set_msg_config  -id {DRC REQP-1840}  -suppress 
set_msg_config  -id {Synth 8-226}  -suppress 
set_msg_config  -id {Drc REQP-1857]}  -suppress 
set_msg_config  -id {Drc REQP-1858]}  -suppress 
set_msg_config  -id {DRC REQP-181}  -suppress 
set_msg_config  -id {DRC REQP-52}  -suppress 
set_msg_config  -id {BD 41-434}  -suppress 
set_msg_config  -id {Designutils 20-1318}  -suppress 
set_msg_config  -id {Common 17-301}  -suppress 
set_msg_config  -id {Pwropt 34-142}  -suppress 
set_msg_config  -id {Common 17-1361}  -suppress 
set_msg_config  -id {Vivado 12-4430}  -suppress 
set_msg_config  -id {Synth 8-312}  -suppress 
set_msg_config  -id {Vivado 12-1790}  -suppress 
set_msg_config  -id {Vivado 12-3645}  -suppress 
set_msg_config  -id {Project 1-486}  -suppress 
set_msg_config  -id {Project 1-560}  -suppress 
set_msg_config  -id {Designutils 20-1307}  -suppress 
set_msg_config  -id {filemgmt 56-12}  -suppress 
set_msg_config  -id {Vivado 12-5470}  -suppress 
set_msg_config  -id {Project 1-841}  -suppress 
set_msg_config  -id {Project 1-863}  -suppress 
set_msg_config  -id {Project 1-840}  -suppress 
set_msg_config  -id {Synth 8-4472}  -suppress 
set_msg_config  -id {Timing 38-3}  -new_severity {INFO} 
set_msg_config  -id {Synth 8-3848}  -new_severity {INFO} 
set_msg_config  -id {Synth 8-3936}  -new_severity {INFO} 
set_msg_config  -id {Synth 8-5733}  -new_severity {INFO} 
set_msg_config  -id {Synth 8-5858}  -new_severity {INFO} 
set_msg_config  -id {Constraints 18-550}  -new_severity {INFO} 
set_msg_config  -id {Vivado 12-1008}  -new_severity {INFO} 
set_msg_config  -id {Power 33-332}  -new_severity {INFO} 
set_msg_config  -id {Synth 8-3512}  -new_severity {ERROR} 
set_msg_config  -id {VRFC 10-664}  -new_severity {ERROR} 
set_msg_config  -id {Synth 8-4480}  -suppress 
set_msg_config  -id {filemgmt 20-1318}  -new_severity {ERROR} 
set_msg_config  -id {IP_Flow 19-1663}  -new_severity {ERROR} 
set_msg_config  -id {IP_Flow 19-11772}  -new_severity {ERROR} 
set_msg_config  -id {Vivado 12-508}  -new_severity {CRITICAL WARNING} 
set_msg_config  -id {Vivado 12-507}  -new_severity {CRITICAL WARNING} 
set_msg_config  -id {Vivado 12-627}  -new_severity {CRITICAL WARNING} 
set_msg_config  -id {Project 1-498}  -new_severity {CRITICAL WARNING} 
set_msg_config  -id {Synth 8-3330}  -new_severity {CRITICAL WARNING} 
set_msg_config  -id {Synth 8-3919}  -new_severity {CRITICAL WARNING} 
set_msg_config  -id {Synth 8-153}  -new_severity {CRITICAL WARNING} 
set_msg_config  -id {Synth 8-3331}  -suppress 
set_msg_config  -id {Synth 8-3295}  -new_severity {CRITICAL WARNING} 
set_msg_config  -id {Synth 8-5835}  -new_severity {CRITICAL WARNING} 
set_msg_config  -id {Route 35-328}  -new_severity {CRITICAL WARNING} 
set_msg_config  -id {Vivado 12-4430}  -new_severity {WARNING} 
set_msg_config  -id {Vivado 12-1387}  -new_severity {WARNING} 
set_msg_config  -id {BD 41-968}  -new_severity {WARNING} 
set_msg_config  -id {Vivado 12-1411}  -new_severity {ERROR} 
set_msg_config  -id {HDL 9-806}  -new_severity {ERROR} 
set_msg_config  -id {Opt 31-80}  -new_severity {ERROR} 
set_msg_config  -id {Route 35-14}  -new_severity {ERROR} 
set_msg_config  -id {Synth 8-3332}  -suppress 
set_msg_config  -id {AVAL-46}  -new_severity {ERROR} 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.cache/wt [current_project]
set_property parent.project_path /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths {/home/vid/.Xilinx/Vivado/2024.2/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part digilentinc.com:arty-a7-100:part0:1.1 [current_project]
set_property ip_repo_paths /home/vid/Desktop/VivadoIpLib [current_project]
update_ip_catalog
set_property ip_output_repo /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library neorv32 {
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_package.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_application_image.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_bootloader_image.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_boot_rom.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_bus.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_cache.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_cfs.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_clint.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_fifo.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_cpu_decompressor.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_cpu_frontend.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_cpu_control.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_cpu_counters.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_cpu_regfile.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_cpu_cp_shifter.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_cpu_cp_muldiv.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_cpu_cp_bitmanip.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_cpu_cp_fpu.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_cpu_cp_cfu.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_cpu_cp_cond.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_cpu_cp_crypto.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_cpu_alu.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_cpu_lsu.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_cpu_pmp.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_cpu_icc.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_cpu.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_crc.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_debug_auth.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_debug_dm.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_debug_dtm.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_dma.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_dmem.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_gpio.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_gptmr.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_hwspinlock.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_imem.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_neoled.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_onewire.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_pwm.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_sdi.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_slink.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_spi.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_sys.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_sysinfo.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_xbus.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_wdt.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_uart.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_twi.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_twd.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_trng.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/core/neorv32_top.vhd
  /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/sources_1/imports/rtl/test_setups/neorv32_test_setup_bootloader.vhd
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/constrs_1/imports/Downloads/Arty_Master.xdc
set_property used_in_implementation false [get_files /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/constrs_1/imports/Downloads/Arty_Master.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/vid/Desktop/Projects/Neorv32_no_ram/Neorv32_no_ram.srcs/utils_1/imports/synth_1/neorv32_test_setup_bootloader.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top neorv32_test_setup_bootloader -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef neorv32_test_setup_bootloader.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file neorv32_test_setup_bootloader_utilization_synth.rpt -pb neorv32_test_setup_bootloader_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
