# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_0_0 || ORIG_REF_NAME==system_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_uartlite_0_0 || ORIG_REF_NAME==system_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_timer_0_0 || ORIG_REF_NAME==system_axi_timer_0_0} -quiet] -quiet

# IP: bd/system/ip/system_microblaze_0_axi_intc_0/system_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_microblaze_0_axi_intc_0 || ORIG_REF_NAME==system_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/system/ip/system_microblaze_0_xlconcat_0/system_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_microblaze_0_xlconcat_0 || ORIG_REF_NAME==system_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/system/ip/system_mdm_1_0/system_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_mdm_1_0 || ORIG_REF_NAME==system_mdm_1_0} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_1_0/system_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_clk_wiz_1_0 || ORIG_REF_NAME==system_clk_wiz_1_0} -quiet] -quiet

# IP: bd/system/ip/system_smartconnect_0_0/system_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_smartconnect_0_0 || ORIG_REF_NAME==system_smartconnect_0_0} -quiet] -quiet

# IP: bd/system/ip/system_microblaze_0_3/system_microblaze_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_microblaze_0_3 || ORIG_REF_NAME==system_microblaze_0_3} -quiet] -quiet

# IP: bd/system/ip/system_dlmb_v10_3/system_dlmb_v10_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_dlmb_v10_3 || ORIG_REF_NAME==system_dlmb_v10_3} -quiet] -quiet

# IP: bd/system/ip/system_ilmb_v10_3/system_ilmb_v10_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ilmb_v10_3 || ORIG_REF_NAME==system_ilmb_v10_3} -quiet] -quiet

# IP: bd/system/ip/system_dlmb_bram_if_cntlr_3/system_dlmb_bram_if_cntlr_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_dlmb_bram_if_cntlr_3 || ORIG_REF_NAME==system_dlmb_bram_if_cntlr_3} -quiet] -quiet

# IP: bd/system/ip/system_ilmb_bram_if_cntlr_3/system_ilmb_bram_if_cntlr_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ilmb_bram_if_cntlr_3 || ORIG_REF_NAME==system_ilmb_bram_if_cntlr_3} -quiet] -quiet

# IP: bd/system/ip/system_lmb_bram_3/system_lmb_bram_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_lmb_bram_3 || ORIG_REF_NAME==system_lmb_bram_3} -quiet] -quiet

# XDC: /home/vid/Desktop/Projects/MicroBlaze_no_ram/MicroBlaze_no_ram.gen/sources_1/bd/system/system_ooc.xdc
