# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.srcs/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_dlmb_v10_2/microblaze_v_preset_dlmb_v10_2.xci
# IP: The module: 'microblaze_v_preset_dlmb_v10_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_dlmb_v10_2/microblaze_v_preset_dlmb_v10_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_v_preset_dlmb_v10_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.srcs/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_dlmb_v10_2/microblaze_v_preset_dlmb_v10_2.xci
# IP: The module: 'microblaze_v_preset_dlmb_v10_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vid/Desktop/Projects/MicroBlaze-V_no_ram/MicroBlaze-V_no_ram.gen/sources_1/bd/microblaze_v_preset/ip/microblaze_v_preset_dlmb_v10_2/microblaze_v_preset_dlmb_v10_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_v_preset_dlmb_v10_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
